# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=256, verbose_name='环境')),
                ('serverip', models.CharField(max_length=256, verbose_name='服务器信息')),
                ('application', models.CharField(max_length=256, verbose_name='应用名')),
                ('port', models.CharField(max_length=256, verbose_name='端口号')),
                ('deployed', models.CharField(max_length=256, verbose_name='部署信息')),
                ('databases', models.CharField(max_length=256, verbose_name='数据库连接')),
                ('remarks', models.CharField(max_length=2560, null=True, verbose_name='备注信息')),
            ],
        ),
    ]
